name: Convert Failure Issues

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  convert-failure:
    if: contains(github.event.issue.labels.*.name, 'failure')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract issue data
        id: extract
        run: |
          ISSUE_ID="INC-$(date +%Y%m%d)-${{ github.event.issue.number }}"
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"

          # Handle multi-line + special chars safely
          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "$TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create failure files
        run: |
          mkdir -p data/failures incidents

          JSON_FILE="data/failures/failures_$(date +%Y%m%d).jsonl"
          MD_FILE="incidents/${ISSUE_ID}.md"

          # Append JSONL entry
          cat >> "$JSON_FILE" <<EOF
{"id":"$ISSUE_ID","model_version":"pending","prompt":"$TITLE","model_output":"(from issue body)","axis_scores":[0,0,0,0,0],"violation_tags":["unspecified"],"sensitive_domain":"unspecified","domain_assessment":"unspecified","human_rationale":"$BODY","decision":"Episode Terminated (Community Report)","approver":"${{ github.actor }}, via GitHub issue","next_action":"Add to failures, schedule rebirth"}
EOF

          # Create incident log
          cat > "$MD_FILE" <<EOF
# Incident Report $ISSUE_ID

**Date:** $(date +%Y-%m-%d)  
**Reported by:** @${{ github.actor }}

## Prompt
\`\`\`
$TITLE
\`\`\`

## Model Output
(see issue body)

## Assessment
Community-submitted failure.

## Decision
Episode Terminated (Community Report)

## Next Action
Add to failures, schedule rebirth.
EOF

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add failure from issue #${{ github.event.issue.number }} ($ISSUE_ID)"
          branch: main
